name: FinalPhantasyCraft
main:  com.catreina.fpc.FinalPhantasyCraft
version: 0.0.1a
author: Catreina
website: https://catreina.com
description: Spigot server plugin for fpc.catreina.com minecraft server
depend: [SkillAPI, PlaceholderAPI]
commands:
  aspectConfig:
    description: Loads Aspect Configuration for new players or purchased Aspect resets
    usage: /AspectConfig
    permission: phantasycraft.aspectconfig
    permission-message: AspectConfig can only be accessed by new players or with the purchase of an Aspect reset.
